### ISSUE TITLE
请问XiangShan上怎么enable smp-difftest？

### ISSUE THREAD

**Issue by RichardRo** [OpenXiangShan/difftest#150]
有这方面的文档吗？

**Comment by poemonsense** [comment]
香山编译时指定为生成双核就可以，在make命令的参数中添加`NUM_CORES=2`

**Comment by RichardRo** [comment]
> 香山编译时指定为生成双核就可以，在make命令的参数中添加`NUM_CORES=2`

我试一下，非常感谢。
