### ISSUE TITLE
Incorrect waveform in co-simulation with DRAMsim3

### ISSUE THREAD

**Issue by shili2017** [OpenXiangShan/difftest#17]
In the current version of difftest, even though some internal signals are directly connected to AXI4 IO signals directly through wire (no registers involved), in the waveform, there's 1 clock cycle delay for these internal signals.

The solution is simple, and works in my OSCPU project. Exchange the order of following two code blocks in `difftest/src/test/csrc/verilator/emu.cpp`, around line 220~240.

```C++
#ifdef WITH_DRAMSIM3
  axi_copy_from_dut_ptr(dut_ptr, axi);
  axi.aw.addr -= 0x80000000UL;
  axi.ar.addr -= 0x80000000UL;
  dramsim3_helper_falling(axi);
  axi_set_dut_ptr(dut_ptr, axi);
#endif

#if VM_TRACE == 1
  if (enable_waveform) {
    auto trap = difftest[0]->get_trap_event();
    uint64_t cycle = trap->cycleCnt;
    uint64_t begin = dut_ptr->io_logCtrl_log_begin;
    uint64_t end   = dut_ptr->io_logCtrl_log_end;
    bool in_range  = (begin <= cycle) && (cycle <= end);
    if (in_range) { tfp->dump(cycle); }
  }
#endif
```

I'm not sure whether it is appropriate to directly submit a pull request, so I raise an issue here :)
(Thank TA Zhibo Hong for helping me on debugging this issue in the OSCPU project.)

**Comment by AugustusWillisWang** [comment]
LGTM, pull request is welcomed :)
