### ISSUE TITLE
请问difftest中的DiffTestState  的定义在哪 我没有找到它

### ISSUE THREAD

**Issue by Taylorsbear720** [OpenXiangShan/difftest#205]

**Comment by Taylorsbear720** [comment]
![image](https://github.com/OpenXiangShan/difftest/assets/99802329/f036a5f4-0148-40d5-ba83-b1bc9bf92e0f)

**Comment by unlsycn** [comment]
`make difftest_verilog`

**Comment by poemonsense** [comment]
产生在自动生成的 `build/generated-src` 目录下，Chisel编译时会自动产生（需要将difftest加入设计项目中，可以参考README的步骤）
