### ISSUE TITLE
Support other CPUs

### ISSUE THREAD

**Issue by changekkk** [OpenXiangShan/difftest#284]
你好，目前看到，Difftest适配了nutshell、rocketchip和xiangshan三个设计工程，想问一下，Difftest从nutshell迁移到rocketchip上，都需要做哪几个方面的修改？或者说，基于一个新的开源核，如果想使用Difftest的话，需要修改哪些内容？

**Comment by poemonsense** [comment]
difftest的README中已经有详细步骤，https://github.com/OpenXiangShan/difftest?tab=readme-ov-file#example-usage

也可以在nutshell/rocket-chip/xiangshan代码中搜索difftest，能展示出所有需要修改的地方，作为案例，https://github.com/search?q=repo%3AOSCPU%2FNutShell%20difftest&type=code

**Comment by changekkk** [comment]
谢谢，我先看看

**Comment by poemonsense** [comment]
Closed. Please feel free to reopen it if there are future issues
