### ISSUE TITLE
Should difftest copy mip register to NEMU when updating mtimecmp in CLINT?

### ISSUE THREAD

**Issue by shili2017** [OpenXiangShan/difftest#30]
Currently I am workign on 3rd ysyx project with Chisel. I skip instruction commit for MMIO accessing. When we update the value of mtimecmp in CLINT, mip will also change, e.g., when we increment mtimecmp in interrupt handler, mtip field in mip register will change from 1 to 0, but difftest doesn't pass this info to NEMU.

My temporary solution (although it is not elegant) is to copy the value of the whole mip register from dut to ref when there's a "skip" instruction in `src/test/csrc/difftest/difftest.cpp:217`.
```C++
  // MMIO accessing should not be a branch or jump, just +2/+4 to get the next pc
  // to skip the checking of an instruction, just copy the reg state to reference design
  if (dut.commit[i].skip) {
    proxy->regcpy(ref_regs_ptr, REF_TO_DIFFTEST);
    ref.csr.this_pc += dut.commit[i].isRVC ? 2 : 4;
    if (dut.commit[i].wen && dut.commit[i].wdest != 0) {
      // TODO: FPR
      ref_regs_ptr[dut.commit[i].wdest] = dut.commit[i].wdata;
    }
    ref.csr.mip = dut.csr.mip;   // THIS IS WHAT I ADDED
    proxy->regcpy(ref_regs_ptr, DIFFTEST_TO_REF);
    return;
  }
```

**Comment by poemonsense** [comment]
Assume `mipReg` is the writable register in CSR and `mipWire` is the external interrupt bits. Difftest should be connected with `mipReg` instead of `mipWire | mipReg`. In this way, difftest does not compare external interrupt bits.
