### ISSUE TITLE
How can the Rocket example provided by Difftest support extended instructions?

### ISSUE THREAD

**Issue by Codemaker-1** [OpenXiangShan/difftest#345]
Hi, maintainers of Difftest. 

Recently, I've been trying to use the Rocket core with Difftest and found that it seems to only support the default extension rv64gc. How can I enable other extensions? (e.g., B extension) . In other words, what efforts should I make to enable Difftest to test the Rocket core with the B extension?

Thanks!

**Comment by poemonsense** [comment]
B extension does not require special handling in DiffTest, since B extension uses the same general-purpose registers as the RV64GC.

Difftest requires extra bundles defined for Vector (`DiffArchVecRegState`, `DiffVecCSRState`) and Hypervisor (`DiffHCSRState`) extensions.

If find it unable to test B extensions, it's most likely you are not using a reference model (NEMU/Spike) ** with B extension enabled**. You may refer to their readme to see how to enable B extension.

**Comment by poemonsense** [comment]
> However, could you provide more information or approaches on how to support the V extension?

Besides XiangShan, which is a good start point, I would recommend just reading the `Difftest.scala`. You can infer from the Bundle definitions that only `DiffArchVecRegState`, `DiffVecCSRState` are for vector (also can be seen from the commit https://github.com/OpenXiangShan/difftest/commit/4ec40ea659a03bc5d131b87d550cd7b6e2af4b23). Thus, the only thing to do is instantiting the corresponding DifftestModule in the design-under-test the same way as other bundles. I believe it would be easy for you to add these bundles in your own design.

**Comment by poemonsense** [comment]
> After the changes, the log output at the top shows:
> 
> ```
> The first instruction of core 0 has commited. Difftest enabled. 
> No instruction of core 0 commits for 500 cycles, maybe get stuck
> (please also check whether a fence.i instruction requires more than 500 cycles to flush the icache)
> Let REF run one more instruction.
> ...
> > The normal instruction flow is displayed below.
> ```
> 
> May I ask if this prompt can be ignored?

It means the design-under-test may be stucked (no commits for 500 cycles) at executing some instruction.

While this cannot be ignored, this suggests something wrong with the design-under-test or how you connect them. DiffInstrCommit does not receive any commit in the last 500 cycles.

If the design does take more than 500 cycles to execute, you may need to enlarge this limit in difftest.h.

However, the more likely reason is, just as it says, the design-under-test may be stucked at some instruction. You can see from the logs displayed for the last instruction executed (marked as `<-`). You can check the design-under-test why this instruction does not commit in the last 500 cycles.

**Comment by poemonsense** [comment]
> Never mind, it seems that Xiangshan is a good example to learn how to support other extensions. You can close this issue whenever you like.

I'm closing this issue to indicate the completion. However, you can still reply to this issue to track future problems.

If you encounter another problem, please feel free to raise a new issue with the corresponding title for the new problem.
