### ISSUE TITLE
Integrating VIP into DiffTest

### ISSUE THREAD

**Issue by changekkk** [OpenXiangShan/difftest#402]
你好，想问下咱们difftest环境是否有尝试接入特定VIP来辅助验证，从环境结构看，能否通过DPI来与VIP通信并启动VIP来进行验证？

Any possibility of integrating VIP into DiffTest via DPI? Does DiffTest provide such practice demo?

**Comment by poemonsense** [comment]
DiffTest主要包含两部分，其一是仿真环境，其二是验证框架，包括面向RISC-V指令、Cache一致性等功能的正确性检查。

VIP主要涉及到的是第二部分的内容，而这部分需要针对不同的验证需求完成配置。DiffTest与VIP不存在兼容性问题，但目前尚未有开源VIP可供RISC-V CPU验证选择，因此我们无法提供案例，如果感兴趣您可以自己尝试接入商业VIP。

**Comment by changekkk** [comment]
您好，谢谢，再问一下，vip采用的是uvm环境，识别相关uvm库，如果接入vip需要同时启动difftest和uvm，二者的通信交互机制，是通过DPI吗？另外，有看到咱们Tltest环境有接入vip的尝试，那么Tltest和DIfftest环境再接入vip方面是否有相似性

**Comment by changekkk** [comment]
您好，想问一下，如果使用UVM通过DPI来启动DIfftest的话，需要驱动哪些接口信号，才能让difftest工作起来？

**Comment by poemonsense** [comment]
Required interfaces have been listed in README.

**Comment by poemonsense** [comment]
Closed this issue assuming all is fixed. Please reopen it if there are still some issues
