### ISSUE TITLE
Relationship between Difftest simulation speed and clock

### ISSUE THREAD

**Issue by changekkk** [OpenXiangShan/difftest#450]
你好，我们在使用Difftest时发现，时钟统一设置成500M情况运行速度相对较快，但设置成800M反而会慢一些，另外，如果设置成跨时钟，比如800和400M两个时钟的话，运行速度最慢，想问下原因是什么？咱们是否对比过不同时钟差异

Hello, when we use Difftest, we find that the running speed is relatively fast when the clock is set to 500M, but it is slower when it is set to 800M. In addition, if it is set to cross-clock, such as 800 and 400M, the running speed is the slowest. What is the reason? Have we compared the differences between different clocks?

**Comment by poemonsense** [comment]
什么叫“时钟统一设置成500M”? 具体指的是什么

What do you mean by "setting the clock to 500M"? What's the change you have made?

**Comment by changekkk** [comment]
我们集成了AXI总线代码，所以时钟包括核内时钟和核外时钟，统一500是指核内外都是500M，跨时钟情况是核内800M，核外400M，发现统一500M速度最快；另外，统一设置成1000M速度也不如500M

**Comment by poemonsense** [comment]
We believe this issue is not related to Difftest. Please refer to the user guide of your RTL simulator.

**Comment by changekkk** [comment]
你好，目前Difftest跑香山核的话，运行Linux的速度大概是每秒多少指令？
