### ISSUE TITLE
difftest运行linux的指令量级问题

### ISSUE THREAD

**Issue by changekkk** [OpenXiangShan/difftest#462]
你好，想问一下Linux.bin有对应的.elf文件吗？另外，我们本地使用环境里的Linux bin和内核配置文件，在本地运行spike指令统计出来有6000多w，但是在香山的difftest环境运行指令数只有400多w，请问下这里导致差异的原因有哪些？

**Comment by poemonsense** [comment]
Please follow the issue template to raise issues. They have been shown when you open this issue. If you do not use the issue template, we'll immediately close the issue without responding.
