### ISSUE TITLE
shmat return value check error

### ISSUE THREAD

**Issue by rrwhx** [OpenXiangShan/difftest#71]
https://github.com/OpenXiangShan/difftest/blob/334f98335db6af0cbb582326aa197d7c941f365b/src/test/csrc/common/lightsss.cpp#L16

man shmt show that:

> On success, shmat() returns the address of the attached shared memory segment; on error, (void *) -1 is returned, and errno is set to indicate the cause of the error.

**Comment by jinyue110** [comment]
Thanks for reminding! :) 

This is a scenario that we didn't cover while running lightSSS. We will fix that soon.
