### ISSUE TITLE
使用Difftest对自己的处理器进行比对工作，显示“address (0x0000000000000000) is out of bound”

### ISSUE THREAD

**Issue by AppDoraemon** [OpenXiangShan/difftest#74]
我想使用Difftest对自己设计的riscv64处理器进行检测，由于我们没有实现C扩展指令集，我选择了NutShell下的ready-to-run/microbench.bin进行测试，但是结果显示

`address (0x0000000000000000) is out of bound {???} [0x0000000000000000, 0x0000000000000000] at pc = 0x0000000000000000`

以及

```
emu: src/device/io/map.c:21: check_bound: Assertion `map != ((void *)0) && addr <= map->high && addr >= map->low' failed.
Aborted (core dumped)
```

我想请问一下是我在有哪里设置的不对，还是说NutShell版本的bin文件不支持最新的difftest了。
如果不兼容的话，请问一下有不带C扩展指令集的microbench的C源码可以方便我重新编译吗？

感谢您的帮助。

**Comment by AppDoraemon** [comment]
> 这是 difftest 跑出问题的提示. 看起来在协同仿真过程中 NEMU 访问了奇怪的地址 `0x0000000000000000`, NEMU 不接受对这段地址的访问.
> 
> 一些可行的策略:
> 
>     1. **可以检查下指令提交时 skip 有没有正确设置, 以及被 skip 的指令结果是否正确**
> 
>     2. 确认下这个报错是在哪个 cycle 触发的? 是在仿真一开始就触发了? 还是仿真过了一段时间才触发?
> 
>     3. 如果不是在仿真一开始就触发, 可以看下错误现场附近的情况, 看看你的处理器有没有发出错误的跳转/访存请求

1. skip这个属性的判断条件应该是怎样的呀？我没有看明白香山和NutShell的具体代码描述。我之前一直是当成mm/io访存指令的判断条件来考虑的。初始的时候microbench都是寄存器计算所以skip设置的是0。同时，我测试了将skip设置为常量1，然后就像difftest源码中描述的，跳转指令无法正确执行了。
2. 这个报错是在仿真一开始就触发了，我这边display了一些指令，显示在我提交第一组指令时就出错了。并且没有显示任何的代码比对内容。
```
index1_PC: 0000000080000000
index1_IR: 00000413
index2_PC: 0000000080000004
index2_IR: 0000f117
The first instruction of core 0 has commited. Difftest enabled. 
address (0x0000000000000000) is out of bound {???} [0x0000000000000000, 0x0000000000000000] at pc = 0x0000000000000000
```
（其中index1和2是一组发射的两条指令）

**Comment by AugustusWillisWang** [comment]
怀疑是 difftest 相关的连线有问题, 导致 skip 后出现异常. skip 可以处理包括 MMIO 指令在内的情况. 它所做的事情是:

1. 将 DUT 中的指令写回结果强制更新到 REF 中
2. 跳过当前指令的比较

参见这里的代码:

https://github.com/OpenXiangShan/difftest/blob/c02950ee1597bcf45af2c9d0b351c1ff99dba5bb/src/test/csrc/difftest/difftest.cpp#L260-L272

请确认所有 difftest 接口的连线正确. 尤其是 `DiffBasicInstrCommitIO` 和 `DiffIntWritebackIO`.
