### ISSUE TITLE
do_store_check的逻辑有bug，if(proxy->store_commit)分支表示的store比对成功，mismatch的打印应该放在else分支中

### ISSUE THREAD

**Issue by huangjiasen100** [OpenXiangShan/difftest#92]
// if (proxy->store_commit(&addr, &data, &mask)) {
    if (proxy->store_commit(&addr, &data, &mask, &nemu_addr, &nemu_data, &nemu_mask)) { // jiasen. 12/8
      eprintf("HJS Difftest::do_store_check proxy->store_commit i = %d success\n", i); // jiasen. 12/7

      // display();
      // printf("Mismatch for store commits %d: \n", i);
      // printf("  REF commits addr 0x%lx, data 0x%lx, mask 0x%x\n", addr, data, mask);
      // printf("  DUT commits addr 0x%lx, data 0x%lx, mask 0x%x\n",
      //   dut.store[i].addr, dut.store[i].data, dut.store[i].mask);
      return 1;
    }
    else { // jiasen. 12/7
      eprintf("HJS Difftest::do_store_check proxy->store_commit i = %d failed\n", i); // jiasen. 12/7
      display();
      eprintf("Mismatch for store commits %d: \n", i);
      eprintf("  DUT commits addr 0x%lx, data 0x%lx, mask 0x%x\n", addr, data, mask);
      eprintf("  REF(NEMU) commits addr 0x%lx, data 0x%lx, mask 0x%x\n", nemu_addr, nemu_data, nemu_mask);
    }

修改如上所示
为了方便调试，同步修改NEMU中的difftest_store_commit以及check_store_commit，令check_store_commit的端口新增NEMU的addr, data, mask信息，以便直接在difftest中监测

**Comment by poemonsense** [comment]
difftest_store_commit返回0代表检查正确
