### ISSUE TITLE
Difftest::Difftest内部没有完成对包括difftest_core_state_t dut在内的对象的初始化

### ISSUE THREAD

**Issue by huangjiasen100** [OpenXiangShan/difftest#93]
dut.csr.this_pc = a3703baed8a56
 dut.csr.mstatus = 40e00333e4728626
 dut.csr.mcause = 88e6e06203f75793
 dut.csr.mepc = 854e85ee86ea8876
 dut.csr.sstatus = 908ff0ef0a676733
 dut.csr.scause = 4e89bac18a5684aa

上述字段全部是不定值

**Comment by poemonsense** [comment]
不需要初始化，会在仿真时被覆盖
