### ISSUE TITLE
RefProxy void (*memcpy)的调用传参错误

### ISSUE THREAD

**Issue by huangjiasen100** [OpenXiangShan/difftest#94]
![image](https://user-images.githubusercontent.com/12743001/206392659-05d2b7ad-8358-41d9-ab6e-064eee769b4a.png)
NEMU daffiest_memcpy的定义中前两个参数是固定的němu_addr (ref), *dut_addr，通过最后一个表示方向的参数在函数体内决定调用memcpy的时候的传参

因此，Difftest框架中调用memcpy的时候也同样应该遵循这一原则，永远固定的第一个参数是ref, 第二个是dut_addr

应该统一修改成proxy->memcpy(golden, &dut.load[i].paddr, len, DUT_TO_DIFFTEST);

**Comment by poemonsense** [comment]
第一个参数是guest上面跑的riscv程序里面的虚拟地址，经过guest_to_host之后转换成x86 nemu下面的ram存储地址
