### ISSUE TITLE
Difftest::step()中实际上没有完成比较，proxy->regcpy(ref_regs_ptr, REF_TO_DUT)将NEMU的reg val全部copy到DUT，二者永远相等

### ISSUE THREAD

**Issue by huangjiasen100** [OpenXiangShan/difftest#95]
应该注释掉这一行

检测到if (dut_regs_ptr[i] != ref_regs_ptr[i])之后，增加assert，可以让程序立即停止，如下所示
==============  REF Regs  ==============
  $0: 0x0000000000000000   ra: 0x0000000000000000   sp: 0x0000000000000000   gp: 0x0000000000000000 
  tp: 0x0000000000000000   t0: 0x0000000000000001   t1: 0x0000000000000000   t2: 0x0000000000000000 
  s0: 0x0000000000000000   s1: 0x0000000000000000   a0: 0x0000000000000000   a1: 0x0000000000000000 
  a2: 0x0000000000000000   a3: 0x0000000000000000   a4: 0x0000000000000000   a5: 0x0000000000000000 
  a6: 0x0000000000000000   a7: 0x0000000000000000   s2: 0x0000000000000000   s3: 0x0000000000000000 
  s4: 0x0000000000000000   s5: 0x0000000000000000   s6: 0x0000000000000000   s7: 0x0000000000000000 
  s8: 0x0000000000000000   s9: 0x0000000000000000  s10: 0x0000000000000000  s11: 0x0000000000000000 
  t3: 0x0000000000000000   t4: 0x0000000000000000   t5: 0x0000000000000000   t6: 0x0000000000000000 
 ft0: 0x6603cf0dd7057a4d  ft1: 0x5b3e034c01d9df56  ft2: 0xc6faa71cb4882fca  ft3: 0xac8f2d18b44e3033 
 ft4: 0x0dd3e856b0bc131c  ft5: 0xbae35a9da9f92940  ft6: 0x7f6df64bf1c5b186  ft7: 0xb4720fc58e09f578 
 fs0: 0xf08842af1e5f21a8  fs1: 0x24a8f0a9ed1aef52  fa0: 0x12a41cf9f928afb0  fa1: 0x72665d147ca91633 
 fa2: 0x952e6bd65d297284  fa3: 0xeb11e7c7bc91cd9c  fa4: 0x72f0cf343b5e4b9c  fa5: 0x0e35c4a60d3f3f97 
 fa6: 0x0cfb7ffb34673dfb  fa7: 0xba73cb93ec983dca  fs2: 0x77fff78baaf4d972  fs3: 0x17effba07ffbefa9 
 fs4: 0xecd198f490e7a599  fs5: 0xcb1e2003519283d0  fs6: 0x28f1913370366398  fs7: 0xb7f1318e7d9d235c 
 fs8: 0x9c9a8046c3a3d81d  fs9: 0x51d3e953b5ab7aa7 fs10: 0x48e97cc9994c6ddb fs11: 0x8ecb12eaa2b1c1e7 
 ft8: 0xb21043888c806c22  ft9: 0xdba911c265bea167 ft10: 0x770fe52f68f001f2 ft11: 0xb52e981edc45e9ea 
pc: 0x0000000010000004 mstatus: 0x0000000a00002000 mcause: 0x0000000000000000 mepc: 0x261286e2e492930c
                       sstatus: 0x0000000200002000 scause: 0x0000000000000000 sepc: 0x0000000000000000
satp: 0x0000000000000000
mip: 0x0000000000000000 mie: 0x0000000000000000 mscratch: 0x0000000000000000 sscratch: 0x0000000000000000
mideleg: 0x0000000000000000 medeleg: 0x0000000000000000
mtval: 0x0000000000000000 stval: 0x8ad80a3f8fae78b6 mtvec: 0x0000000000000000 stvec: 0x0000000000000000
privilege mode:3  pmp: below
 0: cfg:0x00 addr:0x0000000000000000| 1: cfg:0x00 addr:0x0000000000000000
 2: cfg:0x00 addr:0x0000000000000000| 3: cfg:0x00 addr:0x0000000000000000
 4: cfg:0x00 addr:0x0000000000000000| 5: cfg:0x00 addr:0x0000000000000000
 6: cfg:0x00 addr:0x0000000000000000| 7: cfg:0x00 addr:0x0000000000000000
 8: cfg:0x00 addr:0x0000000000000000| 9: cfg:0x00 addr:0x0000000000000000
10: cfg:0x00 addr:0x0000000000000000|11: cfg:0x00 addr:0x0000000000000000
12: cfg:0x00 addr:0x0000000000000000|13: cfg:0x00 addr:0x0000000000000000
14: cfg:0x00 addr:0x0000000000000000|15: cfg:0x00 addr:0x0000000000000000
emu: /data/jiasen/XiangShan/difftest/src/test/csrc/difftest/difftest.cpp:281: virtual int Difftest::step(): Assertion `dut_regs_ptr[i] == ref_regs_ptr[i] && "Error: dup_regs_ptr[i] != ref_regs_ptr[i]"' failed.
priviledgeMode: 3
     t0 different at pc = 0x0010000000, right= 0x0000000000000000, wrong = 0x0000000000000001
     t0 different at pc = 0x0010000000, right= 0x0000000000000000, wrong = 0x0000000000000001

**Comment by poemonsense** [comment]
regcpy是把ref的拷贝到difftest中的 **ref**。对比的数据是difftest中的**ref和dut**
